command /다버리기:
	executable by: console, op
	trigger:
		set {드랍펄스} to true
		loop all items in {플레이어}'s inventory:
			if loop-item is not diamond pickaxe:
				drop loop-item at location of {플레이어}
		clear inventory of {플레이어}
		execute console command "/give %{플레이어}% minecraft:diamond_pickaxe{display:{Name:'{""text"":""다이아곡괭이"",""color"":""blue""}'},Enchantments:[{id:""minecraft:efficiency"",lvl:5}],Unbreakable:1b} 1"
		wait 1 second
		set {드랍펄스} to false

on pickup:
	if {드랍펄스} is true:
		cancel event